### ISSUE TITLE
PHP notices on field configuration page

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/popular_tags#1]
I've just tested this module, looks very useful and works great! However, after enabling the module and going to `admin/structure/types/manage/post/fields/field_tags`, I got two PHP notices:

- Undefined index: popular_tags in popular_tags_field_widget_form_alter() (line 60 of (...)/modules/popular_tags/popular_tags.module)
- Undefined index: popular_tags in popular_tags_form_field_ui_field_edit_form_alter() (line 12 of (...)/modules/popular_tags/popular_tags.module)

The notices appeared once more, IIRC after checking *Enable popular tags* and saving. Then I didn't see the messages again.

Additional info:

- Backdrop version: 1.17.1
- PHP version 7.2.28

**Comment by ghost** [comment]
Thanks @olafgrabienski. Fixed with above commit.

**Comment by olafgrabienski** [comment]
Great, the commit fixes the issue on my test site. Thanks!
