### ISSUE TITLE
Disabling per field doesn't work

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/popular_tags#2]
After enabling *Popular tags* for the "Tags" field in Posts, I wanted to disable it again.

So, I unchecked "Enable popular tags" in the field settings, and the setting was saved. However, new and existing Posts still show the *Popular tags* behavior (even after flushing caches).

Note: the other settings (Limit, Show/Hide links) work fine.

**Comment by ghost** [comment]
Thanks @olafgrabienski. Fixed with the above commit by changing an `isset()` to a `!empty()`.

**Comment by ghost** [comment]
I made a new release with the latest fixes: https://github.com/backdrop-contrib/popular_tags/releases/tag/1.x-1.0.2

**Comment by olafgrabienski** [comment]
> Fixed with the above commit by changing an `isset()` to a `!empty()`.

Thanks a lot, @BWPanda! Updating the module to the new release has fixed the issue for me.
